name: Flutter Windows Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Yeh hamesha latest stable version uthayega
          cache: true # Build speed badhane ke liye

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Video-Downloader-Windows-App
          path: build/windows/x64/runner/Release/