name: Flutter Windows Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4 # Updated version
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.0' # Fixes version issues

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Updated version
        with:
          name: Video-Downloader-Windows-App
          path: build/windows/x64/runner/Release/